*** Ruben López Ranilla
*** Francisco de P. Arjona Jiménez

sload time.maude


fmod ID is 
	protecting STRING .

	sort Id .
	op id : String -> Id [ctor] .
endfm 

view Id from TRIV to ID is	
	sort Elt to Id .
endv

fmod NODE is 
	protecting SET{Id} .
	protecting STRING .
	protecting TIME .

	sort Gateway Node .
	subsort Gateway < Node .
	
	op exclusive : -> Gateway [ctor] .
	op parallel : -> Gateway [ctor] .
	op start : Id Id -> Node [ctor] .
	op end : Id Id -> Node [ctor] .
	op task : Id String Id Id Time Set{Id} -> Node [ctor] .
	op split : Id Gateway Id Set{Id} -> Node [ctor] .
	op merge : Id Gateway Set{Id} Id -> Node [ctor] .
endfm

view Node from TRIV to NODE is	
	sort Elt to Node .
endv


fmod RESOURCE is 
	protecting ID .

	sort Resource .
	op resource : Id Nat Nat -> Resource [ctor] .
endfm

view Resource from TRIV to RESOURCE is	
	sort Elt to Resource .
endv


fmod FLOW is 
	protecting ID .
	protecting TIME .

	sort Flow .
	op flow : Id Time -> Flow [ctor] .
endfm

view Flow from TRIV to FLOW is	
	sort Elt to Flow .
endv


fmod TOKEN is 
	protecting ID .
	protecting TIME .

	sort Token .
	op token : Id Time -> Token [ctor] .
endfm

view Token from TRIV to TOKEN is	
	sort Elt to Token .
endv


mod PROCESS is
	including CONFIGURATION .
	protecting POSRAT-TIME-DOMAIN-WITH-INF .
	protecting ID .
	protecting SET{Node} .
	protecting SET{Flow} .
	protecting SET{Token} .
	protecting SET{Resource} .

	--- class Process | nodes: Set{Node},
	---					flows: Set{Flow},
	---					tokens: Set{Token},
	---					gtime: Time,
	---					resources: Set{Resource} .

	sort Process .
	subsort Process < Cid .

	op Process : -> Process .
	op nodes:_ : Set{Node} -> Attribute [gather (&)] .
    op flows:_ : Set{Flow} -> Attribute [gather (&)] .
    op tokens:_ : Set{Token} -> Attribute [gather (&)] .
    op gtime:_ : Time -> Attribute [gather (&)] .
	op resources:_ : Set{Resource} -> Attribute [gather (&)] .
endm

mod BPMN-SEM is
	protecting PROCESS .

	var name : String .
	var N M : Nat .
	vars idnode idin idout idaux : Id .
	var O : Oid .
	var ids : Set{Id} .
	var nds : Set{Node} .
	var flws : Set{Flow} .
	var tks : Set{Token} .
	var rcs : Set{Resource} .
	var Atts : AttributeSet .
	vars T T' T'' Gtime : Time .

	--- advance of time over a configuration
	op delta : Set{Token} Time -> Set{Token} .
	eq delta(empty, T) = empty .
	eq delta((token(idnode, T'), tks), T) = (token(idnode, T' monus T),delta(tks, T)) .

	--- maximum time elapse (so that no event is lost)
	*** Las puertas necesitan tokens en sus flujos de entrada con timer = 0
	*** Las tareas necesitan tokens en sus flujos de entrada con timer = 0 y todos sus recursos especificados
	op mte : Configuration -> TimeInf .
	eq mte(none) = INF .
	eq mte(< O : Process | nodes: nds, 
						   flows: flws, 
						   tokens: empty, 
						   Atts >) = INF .
	
	*** Task con token a T
	ceq mte(< O : Process | nodes: (task(idnode, name, idin, idout, T, ids),nds), 
							flows: flws, 
							tokens: (token(idin, T), tks),
							resources: rcs, 
							Atts >)
		= minimum(T, mte(< O : Process | nodes: (task(idnode, name, idin, idout, T, ids),nds), 
										   flows: flws, 
										   tokens: tks, 
										   Atts >)) 
		if T =/= 0 .		

	*** Task sin recursos
	ceq mte(< O : Process | nodes: (task(idnode, name, idin, idout, T, ids),nds), 
							flows: flws, 
							tokens: (token(idin, 0), tks),
							resources: rcs, 
							Atts >)
		= minimum(INF, mte(< O : Process | nodes: (task(idnode, name, idin, idout, T, ids),nds), 
										   flows: flws, 
										   tokens: tks, 
										   Atts >)) 
		if not resourcesAvailables(ids,rcs) .											
	
	*** Token con timer > 0 para hacer merge
	ceq mte(< O : Process | nodes: (merge(idnode, parallel, (idin, ids), idout),nds), 
							flows: flws, 
							tokens: (token(idin, T), tks), 
							Atts >) 
        = minimum(T, mte(< O : Process | nodes: (merge(idnode, parallel, (idin, ids), idout),nds), 
															   flows: flws, 
															   tokens: removeTokens(ids,tks), 
															   Atts >)) 
        if T =/= 0 .

	*** Comprobamos timer de los token en flows de entrada
	ceq mte(< O : Process | nodes: (merge(idnode, parallel, (idin, ids), idout),nds), 
							flows: flws, 
							tokens: (token(idin, 0), tks), 
							Atts >) 
        = minimum(INF, mte(< O : Process | nodes: (merge(idnode, parallel, (idin, ids), idout),nds), 
															   flows: flws, 
															   tokens: removeTokens(ids,tks), 
															   Atts >)) 
        if not tokensOnFlowsTime((idnode,ids), tks)  .
	
	*** Si no entra en los otros casos
	eq mte(< O : Process | nodes: nds, flows: flws, tokens: (token(idaux, T), tks), Atts >)
		= minimum(T, mte(< O : Process | nodes: nds, flows: flws, tokens: tks, Atts >)) [owise].


	--- Operador para ver si los recursos de una task están disponibles
	op resourcesAvailables : Set{Id} Set{Resource} -> Bool .
	eq resourcesAvailables(empty,empty) = true .
    eq resourcesAvailables(empty, (resource(idaux, N, M), rcs)) = true .
    eq resourcesAvailables((idaux,ids), (resource(idaux, N, 0), rcs)) = false .
    eq resourcesAvailables((idaux,ids), (resource(idaux, N, M), rcs)) = resourcesAvailables(ids, rcs) [owise] .


	--- Operador para ver si en los flujos de entrada hay un token con el tiempo a 0.
	op tokensOnFlowsTime : Set{Id} Set{Token} -> Bool .
	eq tokensOnFlowsTime(empty, tks) = true .
	eq tokensOnFlowsTime((idnode,ids), (token(idnode, 0), tks)) = tokensOnFlowsTime(ids, tks) .
    eq tokensOnFlowsTime(ids, tks) = false [owise] .


	op addResource : Set{Id} Set{Resource} -> Set{Resource} .
	eq addResource(empty, rcs) = rcs . 
	eq addResource((idnode, ids), (resource(idnode, N, M),rcs)) = (resource(idnode, N, s M), addResource(ids, rcs)) .

	op removeResource : Set{Id} Set{Resource} -> Set{Resource} .
	eq removeResource(empty, rcs) = rcs .
	eq removeResource((idnode, ids), (resource(idnode, N, M),rcs)) = (resource(idnode, N, sd(M, 1)), removeResource(ids, rcs)) .


	op addTokens : Set{Id} Set{Flow} -> Set{Token} . 
    eq addTokens(empty, flws) = empty .
    eq addTokens((idnode, ids), (flow(idnode, T),flws)) = (token(idnode, T), addTokens(ids, flws)) . 
    
    op removeTokens : Set{Id} Set{Token} -> Set{Token} .
    eq removeTokens(empty, tks) = tks .
    eq removeTokens((idnode, ids), (token(idnode, T),tks)) = removeTokens(ids, tks) .
	eq removeTokens((idnode, ids), tks) = removeTokens(ids, tks) [owise] .


	--------------- RLs

	--- tick rule should not advance time beyond expiration of a timer
	crl [tick] : < O : Process | tokens: tks, gtime: Gtime, Atts > 
		=> < O : Process | tokens: delta(tks, T'), gtime: Gtime plus T', Atts > 
		if T' := mte(< O : Process | tokens: tks, gtime: Gtime, Atts >) /\ 0 < T' /\ Gtime < 100 . 


	rl [start] : < O : Process | nodes: (start(idnode, idout), nds), 
								 flows: (flow(idout, T), flws), 
								 tokens: (token(idnode, 0), tks), 
								 Atts >
				=> < O : Process | nodes: (start(idnode, idout), nds), 
								   flows: (flow(idout, T), flws), 
								   tokens: (token(idout, T), tks), 
								   Atts > .


	crl [flowToTask] : < O : Process | nodes: (task(idnode, name, idin, idout, T, ids), nds), 
									   tokens: (token(idin, 0), tks), 
									   resources: rcs, 
									   Atts >
					=> < O : Process | nodes: (task(idnode, name, idin, idout, T, ids), nds), 
									   tokens: (token(idnode, T), tks), 
									   resources: removeResource(ids,rcs), 
									   Atts > 
					if resourcesAvailables(ids,rcs) .


	rl [task] : < O : Process | nodes: (task(idnode, name, idin, idout, T, ids), nds), 
								flows: (flow(idout, T'), flws), 
								tokens: (token(idnode, 0), tks), 
								resources: rcs, Atts >
					=> < O : Process | nodes: (task(idnode, name, idin, idout, T', ids), nds), 
									   flows: (flow(idout, T'), flws), 
									   tokens: (token(idout, T'), tks), 
									   resources: addResource(ids, rcs), 
									   Atts > .


	rl [end] : < O : Process | nodes: (end(idnode, idin), nds), 
							   flows: (flow(idin, T), flws), 
							   tokens: (token(idin, 0), tks), 
							   Atts > 
			=> < O : Process | nodes: (end(idnode, idin), nds), 
							   flows: (flow(idin, T), flws), 
							   tokens: tks, 
							   Atts > .


	rl [mergeExclusive] : < O : Process |  nodes: (merge(idnode, exclusive, (idin, ids), idout), nds), 
							  			   flows: (flow(idout, T), flws), 
							  			   tokens: (token(idin, 0), tks), 
							  			   Atts >
						=> < O : Process | nodes: (merge(idnode, exclusive, (idin, ids), idout), nds), 
										   flows: (flow(idout, T), flws), 
										   tokens: (token(idout, T), tks), 
										   Atts > .
    

	rl [splitExclusive] : < O : Process |  nodes: (split(idnode, exclusive, idin, (idout, ids)), nds), 
										   flows: (flow(idout, T), flws), 
										   tokens: (token(idin, 0), tks), 
										   Atts >
        				=> < O : Process | nodes: (split(idnode, exclusive, idin, (idout, ids)), nds), 
										   flows: (flow(idout, T), flws), 
										   tokens: (token(idout, T), tks), 
										   Atts > .


	crl [mergeParallel] : < O : Process |  nodes: (merge(idnode, parallel, ids, idout), nds), 
										   flows: (flow(idout, T), flws), 
										   tokens: tks, 
										   Atts >
        				=> < O : Process | nodes: (merge(idnode, parallel, ids, idout), nds), 
										   flows: (flow(idout, T), flws), 
										   tokens: (token(idout, T), removeTokens(ids, tks)), 
										   Atts > 
        				if tokensOnFlowsTime(ids, tks) .


	rl [splitParallel] : < O : Process |   nodes: (split(idnode, parallel, idin, (idout, ids)), nds), 
										   flows: (flow(idout, T), flws),
										   tokens: (token(idin, 0), tks), 
										   Atts >
       					=> < O : Process | nodes: (split(idnode, parallel, idin, (idout, ids)), nds), 
										   flows: (flow(idout, T), flws), 
										   tokens: (token(idout, T), addTokens(ids, flws), tks), 
										   Atts > .
    
endm 



eof

search PROCESS =>* < o : Process | tokens: empty, Atts:AttributeSet > .

Maude> search PROCESS =>* < o : Process | tokens: empty, Atts:AttributeSet > .
search in BPMN-EX : PROCESS =>* < o : Process | Atts:AttributeSet,tokens: empty > .

Solution 1 (state 21)
states: 22  rewrites: 244 in 4ms cpu (2ms real) (61000 rewrites/second)
Atts:AttributeSet --> nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id("f28")), split(id(
    "n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))), split(id("n13"),
    parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id("n20"), exclusive,
    id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (id("f15"), id(
    "f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id("f26")), id("f27")),
    merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty), task(id("n03"),
    "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id("n07"),
    "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(id(
    "n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),gtime: 14,resources: (resource(id("car"), 1, 1),
    resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1), resource(id("drone"), 1, 1), resource(id("worker"), 1, 1))

Solution 2 (state 42)
states: 43  rewrites: 508 in 4ms cpu (3ms real) (127000 rewrites/second)
Atts:AttributeSet --> nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id("f28")), split(id(
    "n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))), split(id("n13"),
    parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id("n20"), exclusive,
    id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (id("f15"), id(
    "f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id("f26")), id("f27")),
    merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty), task(id("n03"),
    "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id("n07"),
    "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(id(
    "n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),gtime: 22,resources: (resource(id("car"), 1, 1),
    resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1), resource(id("drone"), 1, 1), resource(id("worker"), 1, 1))

Solution 3 (state 79)
states: 80  rewrites: 1030 in 8ms cpu (7ms real) (128750 rewrites/second)
Atts:AttributeSet --> nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id("f28")), split(id(
    "n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))), split(id("n13"),
    parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id("n20"), exclusive,
    id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (id("f15"), id(
    "f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id("f26")), id("f27")),
    merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty), task(id("n03"),
    "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id("n07"),
    "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(id(
    "n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),gtime: 30,resources: (resource(id("car"), 1, 1),
    resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1), resource(id("drone"), 1, 1), resource(id("worker"), 1, 1))

Solution 4 (state 95)
states: 96  rewrites: 1343 in 12ms cpu (10ms real) (111916 rewrites/second)
Atts:AttributeSet --> nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id("f28")), split(id(
    "n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))), split(id("n13"),
    parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id("n20"), exclusive,
    id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (id("f15"), id(
    "f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id("f26")), id("f27")),
    merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty), task(id("n03"),
    "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id("n07"),
    "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(id(
    "n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),gtime: 32,resources: (resource(id("car"), 1, 1),
    resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1), resource(id("drone"), 1, 1), resource(id("worker"), 1, 1))

Solution 5 (state 129)
states: 130  rewrites: 2019 in 16ms cpu (13ms real) (126187 rewrites/second)
Atts:AttributeSet --> nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id("f28")), split(id(
    "n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))), split(id("n13"),
    parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id("n20"), exclusive,
    id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (id("f15"), id(
    "f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id("f26")), id("f27")),
    merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty), task(id("n03"),
    "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id("n07"),
    "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(id(
    "n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),gtime: 38,resources: (resource(id("car"), 1, 1),
    resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1), resource(id("drone"), 1, 1), resource(id("worker"), 1, 1))

Solution 6 (state 147)
states: 148  rewrites: 2417 in 16ms cpu (17ms real) (151062 rewrites/second)
Atts:AttributeSet --> nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id("f28")), split(id(
    "n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))), split(id("n13"),
    parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id("n20"), exclusive,
    id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (id("f15"), id(
    "f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id("f26")), id("f27")),
    merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty), task(id("n03"),
    "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id("n07"),
    "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(id(
    "n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),gtime: 40,resources: (resource(id("car"), 1, 1),
    resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1), resource(id("drone"), 1, 1), resource(id("worker"), 1, 1))

Solution 7 (state 187)
states: 188  rewrites: 3299 in 24ms cpu (23ms real) (137458 rewrites/second)
Atts:AttributeSet --> nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id("f28")), split(id(
    "n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))), split(id("n13"),
    parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id("n20"), exclusive,
    id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (id("f15"), id(
    "f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id("f26")), id("f27")),
    merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty), task(id("n03"),
    "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id("n07"),
    "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(id(
    "n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),gtime: 46,resources: (resource(id("car"), 1, 1),
    resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1), resource(id("drone"), 1, 1), resource(id("worker"), 1, 1))

Solution 8 (state 209)
states: 210  rewrites: 3775 in 28ms cpu (27ms real) (134821 rewrites/second)
Atts:AttributeSet --> nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id("f28")), split(id(
    "n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))), split(id("n13"),
    parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id("n20"), exclusive,
    id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (id("f15"), id(
    "f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id("f26")), id("f27")),
    merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty), task(id("n03"),
    "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id("n07"),
    "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(id(
    "n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),gtime: 48,resources: (resource(id("car"), 1, 1),
    resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1), resource(id("drone"), 1, 1), resource(id("worker"), 1, 1))

Solution 9 (state 259)
states: 260  rewrites: 4936 in 36ms cpu (34ms real) (137111 rewrites/second)
Atts:AttributeSet --> nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id("f28")), split(id(
    "n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))), split(id("n13"),
    parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id("n20"), exclusive,
    id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (id("f15"), id(
    "f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id("f26")), id("f27")),
    merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty), task(id("n03"),
    "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id("n07"),
    "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(id(
    "n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),gtime: 54,resources: (resource(id("car"), 1, 1),
    resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1), resource(id("drone"), 1, 1), resource(id("worker"), 1, 1))

Solution 10 (state 283)
states: 284  rewrites: 5448 in 40ms cpu (38ms real) (136200 rewrites/second)
Atts:AttributeSet --> nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id("f28")), split(id(
    "n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))), split(id("n13"),
    parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id("n20"), exclusive,
    id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (id("f15"), id(
    "f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id("f26")), id("f27")),
    merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty), task(id("n03"),
    "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id("n07"),
    "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(id(
    "n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),gtime: 56,resources: (resource(id("car"), 1, 1),
    resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1), resource(id("drone"), 1, 1), resource(id("worker"), 1, 1))

Solution 11 (state 333)
states: 334  rewrites: 6617 in 44ms cpu (46ms real) (150386 rewrites/second)
Atts:AttributeSet --> nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id("f28")), split(id(
    "n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))), split(id("n13"),
    parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id("n20"), exclusive,
    id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (id("f15"), id(
    "f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id("f26")), id("f27")),
    merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty), task(id("n03"),
    "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id("n07"),
    "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(id(
    "n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),gtime: 62,resources: (resource(id("car"), 1, 1),
    resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1), resource(id("drone"), 1, 1), resource(id("worker"), 1, 1))

Solution 12 (state 357)
states: 358  rewrites: 7129 in 48ms cpu (51ms real) (148520 rewrites/second)
Atts:AttributeSet --> nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id("f28")), split(id(
    "n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))), split(id("n13"),
    parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id("n20"), exclusive,
    id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (id("f15"), id(
    "f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id("f26")), id("f27")),
    merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty), task(id("n03"),
    "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id("n07"),
    "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(id(
    "n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),gtime: 64,resources: (resource(id("car"), 1, 1),
    resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1), resource(id("drone"), 1, 1), resource(id("worker"), 1, 1))

Solution 13 (state 407)
states: 408  rewrites: 8298 in 56ms cpu (59ms real) (148178 rewrites/second)
Atts:AttributeSet --> nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id("f28")), split(id(
    "n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))), split(id("n13"),
    parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id("n20"), exclusive,
    id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (id("f15"), id(
    "f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id("f26")), id("f27")),
    merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty), task(id("n03"),
    "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id("n07"),
    "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(id(
    "n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),gtime: 70,resources: (resource(id("car"), 1, 1),
    resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1), resource(id("drone"), 1, 1), resource(id("worker"), 1, 1))

Solution 14 (state 431)
states: 432  rewrites: 8810 in 60ms cpu (62ms real) (146833 rewrites/second)
Atts:AttributeSet --> nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id("f28")), split(id(
    "n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))), split(id("n13"),
    parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id("n20"), exclusive,
    id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (id("f15"), id(
    "f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id("f26")), id("f27")),
    merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty), task(id("n03"),
    "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id("n07"),
    "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(id(
    "n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),gtime: 72,resources: (resource(id("car"), 1, 1),
    resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1), resource(id("drone"), 1, 1), resource(id("worker"), 1, 1))

Solution 15 (state 481)
states: 482  rewrites: 9979 in 68ms cpu (69ms real) (146750 rewrites/second)
Atts:AttributeSet --> nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id("f28")), split(id(
    "n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))), split(id("n13"),
    parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id("n20"), exclusive,
    id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (id("f15"), id(
    "f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id("f26")), id("f27")),
    merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty), task(id("n03"),
    "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id("n07"),
    "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(id(
    "n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),gtime: 78,resources: (resource(id("car"), 1, 1),
    resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1), resource(id("drone"), 1, 1), resource(id("worker"), 1, 1))

Solution 16 (state 505)
states: 506  rewrites: 10491 in 68ms cpu (72ms real) (154279 rewrites/second)
Atts:AttributeSet --> nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id("f28")), split(id(
    "n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))), split(id("n13"),
    parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id("n20"), exclusive,
    id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (id("f15"), id(
    "f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id("f26")), id("f27")),
    merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty), task(id("n03"),
    "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id("n07"),
    "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(id(
    "n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),gtime: 80,resources: (resource(id("car"), 1, 1),
    resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1), resource(id("drone"), 1, 1), resource(id("worker"), 1, 1))

Solution 17 (state 555)
states: 556  rewrites: 11660 in 76ms cpu (81ms real) (153421 rewrites/second)
Atts:AttributeSet --> nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id("f28")), split(id(
    "n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))), split(id("n13"),
    parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id("n20"), exclusive,
    id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (id("f15"), id(
    "f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id("f26")), id("f27")),
    merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty), task(id("n03"),
    "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id("n07"),
    "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(id(
    "n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),gtime: 86,resources: (resource(id("car"), 1, 1),
    resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1), resource(id("drone"), 1, 1), resource(id("worker"), 1, 1))

Solution 18 (state 579)
states: 580  rewrites: 12172 in 84ms cpu (85ms real) (144904 rewrites/second)
Atts:AttributeSet --> nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id("f28")), split(id(
    "n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))), split(id("n13"),
    parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id("n20"), exclusive,
    id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (id("f15"), id(
    "f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id("f26")), id("f27")),
    merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty), task(id("n03"),
    "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id("n07"),
    "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(id(
    "n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),gtime: 88,resources: (resource(id("car"), 1, 1),
    resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1), resource(id("drone"), 1, 1), resource(id("worker"), 1, 1))

Solution 19 (state 629)
states: 630  rewrites: 13341 in 92ms cpu (93ms real) (145010 rewrites/second)
Atts:AttributeSet --> nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id("f28")), split(id(
    "n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))), split(id("n13"),
    parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id("n20"), exclusive,
    id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (id("f15"), id(
    "f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id("f26")), id("f27")),
    merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty), task(id("n03"),
    "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id("n07"),
    "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(id(
    "n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),gtime: 94,resources: (resource(id("car"), 1, 1),
    resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1), resource(id("drone"), 1, 1), resource(id("worker"), 1, 1))

Solution 20 (state 653)
states: 654  rewrites: 13853 in 92ms cpu (97ms real) (150576 rewrites/second)
Atts:AttributeSet --> nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id("f28")), split(id(
    "n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))), split(id("n13"),
    parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id("n20"), exclusive,
    id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (id("f15"), id(
    "f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id("f26")), id("f27")),
    merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty), task(id("n03"),
    "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id("n07"),
    "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(id(
    "n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),gtime: 96,resources: (resource(id("car"), 1, 1),
    resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1), resource(id("drone"), 1, 1), resource(id("worker"), 1, 1))

No more solutions.
states: 699  rewrites: 15091 in 104ms cpu (106ms real) (145105 rewrites/second)


- - - - - - - - - - - - - - 

search PROCESS =>! C:Configuration .

Maude> search PROCESS =>! C:Configuration .
search in BPMN-EX : PROCESS =>! C:Configuration .

Solution 1 (state 21)
states: 24  rewrites: 284 in 4ms cpu (1ms real) (71000 rewrites/second)
C:Configuration --> < o : Process | nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id(
    "f28")), split(id("n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))),
    split(id("n13"), parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id(
    "n20"), exclusive, id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (
    id("f15"), id("f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id(
    "f26")), id("f27")), merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty),
    task(id("n03"), "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id(
    "n07"), "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(
    id("n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),tokens: empty,gtime: 14,resources: (resource(id(
    "car"), 1, 1), resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1), resource(id("drone"), 1, 1), resource(id("worker"), 1, 1)) >

Solution 2 (state 42)
states: 47  rewrites: 557 in 4ms cpu (3ms real) (139250 rewrites/second)
C:Configuration --> < o : Process | nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id(
    "f28")), split(id("n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))),
    split(id("n13"), parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id(
    "n20"), exclusive, id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (
    id("f15"), id("f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id(
    "f26")), id("f27")), merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty),
    task(id("n03"), "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id(
    "n07"), "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(
    id("n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),tokens: empty,gtime: 22,resources: (resource(id(
    "car"), 1, 1), resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1), resource(id("drone"), 1, 1), resource(id("worker"), 1, 1)) >

Solution 3 (state 79)
states: 87  rewrites: 1141 in 8ms cpu (6ms real) (142625 rewrites/second)
C:Configuration --> < o : Process | nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id(
    "f28")), split(id("n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))),
    split(id("n13"), parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id(
    "n20"), exclusive, id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (
    id("f15"), id("f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id(
    "f26")), id("f27")), merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty),
    task(id("n03"), "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id(
    "n07"), "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(
    id("n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),tokens: empty,gtime: 30,resources: (resource(id(
    "car"), 1, 1), resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1), resource(id("drone"), 1, 1), resource(id("worker"), 1, 1)) >

Solution 4 (state 95)
states: 101  rewrites: 1458 in 8ms cpu (8ms real) (182250 rewrites/second)
C:Configuration --> < o : Process | nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id(
    "f28")), split(id("n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))),
    split(id("n13"), parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id(
    "n20"), exclusive, id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (
    id("f15"), id("f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id(
    "f26")), id("f27")), merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty),
    task(id("n03"), "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id(
    "n07"), "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(
    id("n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),tokens: empty,gtime: 32,resources: (resource(id(
    "car"), 1, 1), resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1), resource(id("drone"), 1, 1), resource(id("worker"), 1, 1)) >

Solution 5 (state 129)
states: 138  rewrites: 2171 in 16ms cpu (13ms real) (135687 rewrites/second)
C:Configuration --> < o : Process | nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id(
    "f28")), split(id("n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))),
    split(id("n13"), parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id(
    "n20"), exclusive, id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (
    id("f15"), id("f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id(
    "f26")), id("f27")), merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty),
    task(id("n03"), "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id(
    "n07"), "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(
    id("n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),tokens: empty,gtime: 38,resources: (resource(id(
    "car"), 1, 1), resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1), resource(id("drone"), 1, 1), resource(id("worker"), 1, 1)) >

Solution 6 (state 147)
states: 154  rewrites: 2570 in 16ms cpu (15ms real) (160625 rewrites/second)
C:Configuration --> < o : Process | nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id(
    "f28")), split(id("n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))),
    split(id("n13"), parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id(
    "n20"), exclusive, id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (
    id("f15"), id("f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id(
    "f26")), id("f27")), merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty),
    task(id("n03"), "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id(
    "n07"), "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(
    id("n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),tokens: empty,gtime: 40,resources: (resource(id(
    "car"), 1, 1), resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1), resource(id("drone"), 1, 1), resource(id("worker"), 1, 1)) >

Solution 7 (state 187)
states: 198  rewrites: 3469 in 20ms cpu (20ms real) (173450 rewrites/second)
C:Configuration --> < o : Process | nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id(
    "f28")), split(id("n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))),
    split(id("n13"), parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id(
    "n20"), exclusive, id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (
    id("f15"), id("f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id(
    "f26")), id("f27")), merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty),
    task(id("n03"), "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id(
    "n07"), "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(
    id("n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),tokens: empty,gtime: 46,resources: (resource(id(
    "car"), 1, 1), resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1), resource(id("drone"), 1, 1), resource(id("worker"), 1, 1)) >

Solution 8 (state 209)
states: 218  rewrites: 3993 in 24ms cpu (23ms real) (166375 rewrites/second)
C:Configuration --> < o : Process | nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id(
    "f28")), split(id("n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))),
    split(id("n13"), parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id(
    "n20"), exclusive, id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (
    id("f15"), id("f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id(
    "f26")), id("f27")), merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty),
    task(id("n03"), "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id(
    "n07"), "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(
    id("n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),tokens: empty,gtime: 48,resources: (resource(id(
    "car"), 1, 1), resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1), resource(id("drone"), 1, 1), resource(id("worker"), 1, 1)) >

Solution 9 (state 259)
states: 271  rewrites: 5126 in 32ms cpu (32ms real) (160187 rewrites/second)
C:Configuration --> < o : Process | nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id(
    "f28")), split(id("n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))),
    split(id("n13"), parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id(
    "n20"), exclusive, id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (
    id("f15"), id("f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id(
    "f26")), id("f27")), merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty),
    task(id("n03"), "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id(
    "n07"), "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(
    id("n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),tokens: empty,gtime: 54,resources: (resource(id(
    "car"), 1, 1), resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1), resource(id("drone"), 1, 1), resource(id("worker"), 1, 1)) >

Solution 10 (state 283)
states: 292  rewrites: 5674 in 36ms cpu (35ms real) (157611 rewrites/second)
C:Configuration --> < o : Process | nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id(
    "f28")), split(id("n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))),
    split(id("n13"), parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id(
    "n20"), exclusive, id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (
    id("f15"), id("f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id(
    "f26")), id("f27")), merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty),
    task(id("n03"), "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id(
    "n07"), "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(
    id("n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),tokens: empty,gtime: 56,resources: (resource(id(
    "car"), 1, 1), resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1), resource(id("drone"), 1, 1), resource(id("worker"), 1, 1)) >

Solution 11 (state 333)
states: 345  rewrites: 6807 in 44ms cpu (43ms real) (154704 rewrites/second)
C:Configuration --> < o : Process | nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id(
    "f28")), split(id("n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))),
    split(id("n13"), parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id(
    "n20"), exclusive, id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (
    id("f15"), id("f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id(
    "f26")), id("f27")), merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty),
    task(id("n03"), "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id(
    "n07"), "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(
    id("n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),tokens: empty,gtime: 62,resources: (resource(id(
    "car"), 1, 1), resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1), resource(id("drone"), 1, 1), resource(id("worker"), 1, 1)) >

Solution 12 (state 357)
states: 366  rewrites: 7355 in 48ms cpu (48ms real) (153229 rewrites/second)
C:Configuration --> < o : Process | nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id(
    "f28")), split(id("n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))),
    split(id("n13"), parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id(
    "n20"), exclusive, id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (
    id("f15"), id("f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id(
    "f26")), id("f27")), merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty),
    task(id("n03"), "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id(
    "n07"), "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(
    id("n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),tokens: empty,gtime: 64,resources: (resource(id(
    "car"), 1, 1), resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1), resource(id("drone"), 1, 1), resource(id("worker"), 1, 1)) >

Solution 13 (state 407)
states: 419  rewrites: 8488 in 56ms cpu (55ms real) (151571 rewrites/second)
C:Configuration --> < o : Process | nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id(
    "f28")), split(id("n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))),
    split(id("n13"), parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id(
    "n20"), exclusive, id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (
    id("f15"), id("f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id(
    "f26")), id("f27")), merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty),
    task(id("n03"), "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id(
    "n07"), "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(
    id("n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),tokens: empty,gtime: 70,resources: (resource(id(
    "car"), 1, 1), resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1), resource(id("drone"), 1, 1), resource(id("worker"), 1, 1)) >

Solution 14 (state 431)
states: 440  rewrites: 9036 in 60ms cpu (59ms real) (150600 rewrites/second)
C:Configuration --> < o : Process | nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id(
    "f28")), split(id("n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))),
    split(id("n13"), parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id(
    "n20"), exclusive, id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (
    id("f15"), id("f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id(
    "f26")), id("f27")), merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty),
    task(id("n03"), "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id(
    "n07"), "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(
    id("n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),tokens: empty,gtime: 72,resources: (resource(id(
    "car"), 1, 1), resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1), resource(id("drone"), 1, 1), resource(id("worker"), 1, 1)) >

Solution 15 (state 481)
states: 493  rewrites: 10169 in 68ms cpu (68ms real) (149544 rewrites/second)
C:Configuration --> < o : Process | nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id(
    "f28")), split(id("n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))),
    split(id("n13"), parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id(
    "n20"), exclusive, id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (
    id("f15"), id("f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id(
    "f26")), id("f27")), merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty),
    task(id("n03"), "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id(
    "n07"), "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(
    id("n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),tokens: empty,gtime: 78,resources: (resource(id(
    "car"), 1, 1), resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1), resource(id("drone"), 1, 1), resource(id("worker"), 1, 1)) >

Solution 16 (state 505)
states: 514  rewrites: 10717 in 72ms cpu (71ms real) (148847 rewrites/second)
C:Configuration --> < o : Process | nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id(
    "f28")), split(id("n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))),
    split(id("n13"), parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id(
    "n20"), exclusive, id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (
    id("f15"), id("f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id(
    "f26")), id("f27")), merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty),
    task(id("n03"), "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id(
    "n07"), "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(
    id("n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),tokens: empty,gtime: 80,resources: (resource(id(
    "car"), 1, 1), resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1), resource(id("drone"), 1, 1), resource(id("worker"), 1, 1)) >

Solution 17 (state 555)
states: 567  rewrites: 11850 in 80ms cpu (80ms real) (148125 rewrites/second)
C:Configuration --> < o : Process | nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id(
    "f28")), split(id("n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))),
    split(id("n13"), parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id(
    "n20"), exclusive, id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (
    id("f15"), id("f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id(
    "f26")), id("f27")), merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty),
    task(id("n03"), "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id(
    "n07"), "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(
    id("n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),tokens: empty,gtime: 86,resources: (resource(id(
    "car"), 1, 1), resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1), resource(id("drone"), 1, 1), resource(id("worker"), 1, 1)) >

Solution 18 (state 579)
states: 588  rewrites: 12398 in 84ms cpu (83ms real) (147595 rewrites/second)
C:Configuration --> < o : Process | nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id(
    "f28")), split(id("n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))),
    split(id("n13"), parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id(
    "n20"), exclusive, id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (
    id("f15"), id("f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id(
    "f26")), id("f27")), merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty),
    task(id("n03"), "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id(
    "n07"), "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(
    id("n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),tokens: empty,gtime: 88,resources: (resource(id(
    "car"), 1, 1), resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1), resource(id("drone"), 1, 1), resource(id("worker"), 1, 1)) >

Solution 19 (state 629)
states: 641  rewrites: 13531 in 92ms cpu (90ms real) (147076 rewrites/second)
C:Configuration --> < o : Process | nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id(
    "f28")), split(id("n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))),
    split(id("n13"), parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id(
    "n20"), exclusive, id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (
    id("f15"), id("f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id(
    "f26")), id("f27")), merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty),
    task(id("n03"), "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id(
    "n07"), "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(
    id("n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),tokens: empty,gtime: 94,resources: (resource(id(
    "car"), 1, 1), resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1), resource(id("drone"), 1, 1), resource(id("worker"), 1, 1)) >

Solution 20 (state 653)
states: 662  rewrites: 14079 in 92ms cpu (93ms real) (153032 rewrites/second)
C:Configuration --> < o : Process | nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id(
    "f28")), split(id("n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))),
    split(id("n13"), parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id(
    "n20"), exclusive, id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (
    id("f15"), id("f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id(
    "f26")), id("f27")), merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty),
    task(id("n03"), "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id(
    "n07"), "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(
    id("n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),tokens: empty,gtime: 96,resources: (resource(id(
    "car"), 1, 1), resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1), resource(id("drone"), 1, 1), resource(id("worker"), 1, 1)) >

Solution 21 (state 683)
states: 692  rewrites: 14765 in 100ms cpu (100ms real) (147650 rewrites/second)
C:Configuration --> < o : Process | nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id(
    "f28")), split(id("n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))),
    split(id("n13"), parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id(
    "n20"), exclusive, id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (
    id("f15"), id("f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id(
    "f26")), id("f27")), merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty),
    task(id("n03"), "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id(
    "n07"), "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(
    id("n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),tokens: token(id("f04"), 2),gtime: 100,
    resources: (resource(id("car"), 1, 1), resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1), resource(id("drone"), 1, 1), resource(id(
    "worker"), 1, 1)) >

Solution 22 (state 684)
states: 692  rewrites: 14774 in 100ms cpu (100ms real) (147740 rewrites/second)
C:Configuration --> < o : Process | nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id(
    "f28")), split(id("n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))),
    split(id("n13"), parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id(
    "n20"), exclusive, id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (
    id("f15"), id("f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id(
    "f26")), id("f27")), merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty),
    task(id("n03"), "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id(
    "n07"), "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(
    id("n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),tokens: token(id("f05"), 2),gtime: 100,
    resources: (resource(id("car"), 1, 1), resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1), resource(id("drone"), 1, 1), resource(id(
    "worker"), 1, 1)) >

Solution 23 (state 685)
states: 692  rewrites: 14782 in 100ms cpu (101ms real) (147820 rewrites/second)
C:Configuration --> < o : Process | nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id(
    "f28")), split(id("n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))),
    split(id("n13"), parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id(
    "n20"), exclusive, id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (
    id("f15"), id("f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id(
    "f26")), id("f27")), merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty),
    task(id("n03"), "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id(
    "n07"), "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(
    id("n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),tokens: token(id("f06"), 2),gtime: 100,
    resources: (resource(id("car"), 1, 1), resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1), resource(id("drone"), 1, 1), resource(id(
    "worker"), 1, 1)) >

Solution 24 (state 686)
states: 692  rewrites: 14790 in 104ms cpu (101ms real) (142211 rewrites/second)
C:Configuration --> < o : Process | nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id(
    "f28")), split(id("n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))),
    split(id("n13"), parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id(
    "n20"), exclusive, id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (
    id("f15"), id("f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id(
    "f26")), id("f27")), merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty),
    task(id("n03"), "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id(
    "n07"), "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(
    id("n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),tokens: token(id("f08"), 2),gtime: 100,
    resources: (resource(id("car"), 1, 1), resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1), resource(id("drone"), 1, 1), resource(id(
    "worker"), 1, 1)) >

Solution 25 (state 687)
states: 692  rewrites: 14798 in 104ms cpu (101ms real) (142288 rewrites/second)
C:Configuration --> < o : Process | nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id(
    "f28")), split(id("n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))),
    split(id("n13"), parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id(
    "n20"), exclusive, id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (
    id("f15"), id("f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id(
    "f26")), id("f27")), merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty),
    task(id("n03"), "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id(
    "n07"), "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(
    id("n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),tokens: token(id("n07"), 2),gtime: 100,
    resources: (resource(id("car"), 1, 1), resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1), resource(id("drone"), 1, 1), resource(id(
    "worker"), 1, 1)) >

Solution 26 (state 688)
states: 692  rewrites: 14830 in 104ms cpu (102ms real) (142596 rewrites/second)
C:Configuration --> < o : Process | nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id(
    "f28")), split(id("n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))),
    split(id("n13"), parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id(
    "n20"), exclusive, id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (
    id("f15"), id("f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id(
    "f26")), id("f27")), merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty),
    task(id("n03"), "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id(
    "n07"), "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(
    id("n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),tokens: (token(id("f14"), 2), token(id("f15"),
    2), token(id("f16"), 2)),gtime: 100,resources: (resource(id("car"), 1, 1), resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1),
    resource(id("drone"), 1, 1), resource(id("worker"), 1, 1)) >

Solution 27 (state 695)
states: 699  rewrites: 15047 in 104ms cpu (104ms real) (144682 rewrites/second)
C:Configuration --> < o : Process | nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id(
    "f28")), split(id("n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))),
    split(id("n13"), parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id(
    "n20"), exclusive, id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (
    id("f15"), id("f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id(
    "f26")), id("f27")), merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty),
    task(id("n03"), "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id(
    "n07"), "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(
    id("n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),tokens: (token(id("f18"), 2), token(id("f19"),
    0), token(id("f21"), 0)),gtime: 100,resources: (resource(id("car"), 1, 1), resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1),
    resource(id("drone"), 1, 1), resource(id("worker"), 1, 1)) >

Solution 28 (state 696)
states: 699  rewrites: 15065 in 104ms cpu (105ms real) (144855 rewrites/second)
C:Configuration --> < o : Process | nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id(
    "f28")), split(id("n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))),
    split(id("n13"), parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id(
    "n20"), exclusive, id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (
    id("f15"), id("f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id(
    "f26")), id("f27")), merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty),
    task(id("n03"), "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id(
    "n07"), "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(
    id("n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),tokens: (token(id("f21"), 0), token(id("f23"),
    2)),gtime: 100,resources: (resource(id("car"), 1, 1), resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1), resource(id("drone"), 1, 1),
    resource(id("worker"), 1, 1)) >

Solution 29 (state 697)
states: 699  rewrites: 15083 in 108ms cpu (105ms real) (139657 rewrites/second)
C:Configuration --> < o : Process | nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id(
    "f28")), split(id("n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))),
    split(id("n13"), parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id(
    "n20"), exclusive, id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (
    id("f15"), id("f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id(
    "f26")), id("f27")), merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty),
    task(id("n03"), "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id(
    "n07"), "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(
    id("n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),tokens: (token(id("f21"), 0), token(id("f24"),
    2)),gtime: 100,resources: (resource(id("car"), 1, 1), resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1), resource(id("drone"), 1, 1),
    resource(id("worker"), 1, 1)) >

Solution 30 (state 698)
states: 699  rewrites: 15091 in 108ms cpu (106ms real) (139731 rewrites/second)
C:Configuration --> < o : Process | nodes: (start(id("n00"), id("f00")), end(id("n05"), id("f06")), end(id("n08"), id("f13")), end(id("n25"), id(
    "f28")), split(id("n04"), exclusive, id("f03"), (id("f04"), id("f05"), id("f06"))), split(id("n10"), exclusive, id("f08"), (id("f09"), id("f10"))),
    split(id("n13"), parallel, id("f29"), (id("f17"), id("f21"))), split(id("n15"), parallel, id("f11"), (id("f14"), id("f15"), id("f16"))), split(id(
    "n20"), exclusive, id("f22"), (id("f23"), id("f24"))), merge(id("n02"), exclusive, (id("f01"), id("f04")), id("f02")), merge(id("n17"), parallel, (
    id("f15"), id("f17")), id("f18")), merge(id("n19"), parallel, (id("f19"), id("f20")), id("f22")), merge(id("n23"), exclusive, (id("f25"), id(
    "f26")), id("f27")), merge(id("n24"), parallel, (id("f21"), id("f27")), id("f28")), task(id("n01"), "Sign in", id("f00"), id("f01"), 2, empty),
    task(id("n03"), "Search products", id("f02"), id("f03"), 2, empty), task(id("n06"), "Make an order", id("f05"), id("f07"), 2, empty), task(id(
    "n07"), "Fill in feedback form", id("f12"), id("f13"), 2, empty), task(id("n09"), "Check availability", id("f07"), id("f08"), 2, id("clerk")), task(
    id("n11"), "Cancel order", id("f09"), id("f12"), 2, id("clerk")), task(id("n12"), "Pay for order", id("f14"), id("f29"), 2, empty), task(id("n14"),
    "Confirm order", id("f10"), id("f11"), 2, id("clerk")), task(id("n16"), "Prepare parcel", id("f16"), id("f19"), 2, id("worker")), task(id("n18"),
    "Payment validation", id("f18"), id("f20"), 2, empty), task(id("n21"), "Deliver by drone", id("f23"), id("f25"), 2, id("drone")), task(id("n22"),
    "Deliver by car", id("f24"), id("f26"), 2, (id("car"), id("delivery man")))),flows: (flow(id("f00"), 2), flow(id("f01"), 2), flow(id("f02"), 2),
    flow(id("f03"), 2), flow(id("f04"), 2), flow(id("f05"), 2), flow(id("f06"), 2), flow(id("f07"), 2), flow(id("f08"), 2), flow(id("f09"), 2), flow(id(
    "f10"), 2), flow(id("f11"), 2), flow(id("f12"), 2), flow(id("f13"), 2), flow(id("f14"), 2), flow(id("f15"), 2), flow(id("f16"), 2), flow(id("f17"),
    2), flow(id("f18"), 2), flow(id("f19"), 2), flow(id("f20"), 2), flow(id("f21"), 2), flow(id("f22"), 2), flow(id("f23"), 2), flow(id("f24"), 2),
    flow(id("f25"), 2), flow(id("f26"), 2), flow(id("f27"), 2), flow(id("f28"), 2), flow(id("f29"), 2)),tokens: token(id("f28"), 2),gtime: 100,
    resources: (resource(id("car"), 1, 1), resource(id("clerk"), 1, 1), resource(id("delivery man"), 1, 1), resource(id("drone"), 1, 1), resource(id(
    "worker"), 1, 1)) >

No more solutions.
states: 699  rewrites: 15091 in 108ms cpu (106ms real) (139731 rewrites/second)
